### ISSUE TITLE
Crash when log_dir: points to an inaccessible location

### ISSUE THREAD

**Issue by nerosnm** [osa1/tiny#132]
When I try to run `tiny` on macOS 10.15 (19A512f), it panics with this output:

```
Any mentions to you will be listed here.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1084:5
mentions                                                                                                                                                                    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Running with backtrace gives me:

```
Any mentions to you will be listed here.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1084:5
mentions                                                                                                                                                                    stack backtrace:
                                                                                                                                                                                               0: std::panicking::default_hook::{{closure}}
                           1: std::panicking::rust_panic_with_hook
                                                                     2: std::panicking::continue_panic_fmt
                                                                                                             3: rust_begin_unwind
                                                                                                                                    4: core::panicking::panic_fmt
                                                                                                                                                                    5: core::result::unwrap_failed
                                                                                                                                                                                                     6: tiny::Tiny::run
       7: tiny::main
                       8: std::rt::lang_start::{{closure}}
                                                             9: main
```

I built `tiny` with rustc 1.38.0-nightly (d3f8a0b5d 2019-08-04) from commit 35752a3.

**Comment by osa1** [comment]
Thanks for reporting. Can you try with a debug build, running tiny with `tiny 2>stderr` ? After the panic the file `stderr` should contain better formatted and more detailed backtrace. Just run it with

```
$ cargo run 2>stderr
```

Thanks!

**Comment by sorenmortensen** [comment]
Sure:

```
$ env RUST_BACKTRACE=1 cargo +nightly run 2>stderr; bat -p stderr
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/tiny`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: std::panicking::begin_panic
  10: std::panicking::begin_panic
  11: core::result::Result<T,E>::unwrap
             at /rustc/d3f8a0b5dfddfe443d9db1f1da18348dbceb0e47/src/libcore/result.rs:852
  12: tiny::logger::Logger::new
             at src/logger.rs:55
  13: tiny::Tiny::run
             at src/lib.rs:176
  14: tiny::run
             at src/lib.rs:105
  15: tiny::main
             at bin/main.rs:4
  16: std::rt::lang_start::{{closure}}
             at /rustc/d3f8a0b5dfddfe443d9db1f1da18348dbceb0e47/src/libstd/rt.rs:64
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: std::panicking::try
             at src/libstd/panicking.rs:275
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  23: std::rt::lang_start
             at /rustc/d3f8a0b5dfddfe443d9db1f1da18348dbceb0e47/src/libstd/rt.rs:64
  24: tiny::main
```

**Comment by osa1** [comment]
So it seems like tiny is failing to open the log file. I'd check the log directory in `~/.tinyrc.yml` (see the line starting with `log_dir:`) and make sure it's a valid path. The log file tiny tries to create is `<log_dir>/debug.log` (where `<log_dir>` is the `log_dir` field in your `tinyrc.yml`).

We should do a better job at handling file system errors.

**Comment by sorenmortensen** [comment]
Ah, this is becoming more interesting now.

I checked my `~/.tinyrc.yml` and found that `log_dir:` was pointing to `/Users/soren/.tiny_logs`, which is an absolute path to a directory in the home folder of the *other account* on my machine. This is my fault and due to config file management/syncing between machines/accounts, and explains why the error was a "permission denied" error 13 rather than a "no such file or directory" error 2.

However, it seems the reason I had an absolute path in my config file like this is because, when I change it to `~/.tiny_logs`,

- `tiny` launches without crashing, but
- doesn't create this directory when it runs, and
- doesn't write any logs inside the directory if I create the directory myself before running it.

If I change it to `/Users/snm/.tiny_logs`, which is a correct path inside the home folder of this account, `tiny` both creates the directory and writes logs to it.

The config value `$HOME/.tiny_logs` doesn't work either.

Is there any way support could be added for either the `~/.tiny_logs` or the `$HOME/.tiny_logs` syntax in the config file, please? This would allow me to remove the absolute path from my config file, which would eliminate this crash and allow my config file to be truly machine- and user-independent. I'm happy to file a separate issue for this if you'd like me to.

**Comment by osa1** [comment]
So you want to support `~` syntax and shell variables. I think this shouldn't be too hard to implement, but I can't tell how off the top of my head. I'm lacking time to work on tiny these days so I'm afraid these will have to be implemented by someone other than me. Would you be willing to implement this yourself? I'd be happy to help if you have any questions.

**Comment by sorenmortensen** [comment]
No worries, I can look into that. Thanks for all your help!
