### ISSUE TITLE
"Unknown IRC color" panic

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#34]
This happened today:

```
thread 'main' panicked at 'Unknown irc color: 30', src/tui/msg_area/line.rs:429:12
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:69
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: tiny::tui::msg_area::line::translate_irc_control_chars::push_color
   6: tiny::tui::msg_area::line::Line::add_text
   7: tiny::tui::messaging::MessagingUI::add_privmsg
   8: tiny::tui::tabbed::Tabbed::add_privmsg
   9: tiny::Tiny::handle_conn_ev
  10: tiny::run
  11: main
  12: __libc_start_main
  13: _start
```

**Comment by osa1** [comment]
Just checked the raw logs and indeed someone actually sent `[\x03 '3' '0']`.
